#############################################################################
# Makefile for building: test
# Generated by qmake (3.0) (Qt 5.0.1) on: Fri Sep 13 15:17:52 2013
# Project:  test.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 -o Makefile test.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/usr/share/qt5/mkspecs/linux-g++-64 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -lsfml-system -lsfml-window -lsfml-graphics -lsfml-audio -lGL 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Game.cpp \
		Tools.cpp \
		Shader.cpp 
OBJECTS       = main.o \
		Game.o \
		Tools.o \
		Shader.o
DIST          = /usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/shell-unix.conf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/unix/default_pre.prf \
		/usr/share/qt5/mkspecs/features/release.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/shared.prf \
		/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		test.pro \
		test.pro
QMAKE_TARGET  = test
DESTDIR       = 
TARGET        = test


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: test.pro /usr/share/qt5/mkspecs/linux-g++-64/qmake.conf /usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/shell-unix.conf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/unix/default_pre.prf \
		/usr/share/qt5/mkspecs/features/release.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/shared.prf \
		/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		test.pro
	$(QMAKE) -spec linux-g++-64 -o Makefile test.pro
/usr/share/qt5/mkspecs/features/spec_pre.prf:
/usr/share/qt5/mkspecs/common/shell-unix.conf:
/usr/share/qt5/mkspecs/common/unix.conf:
/usr/share/qt5/mkspecs/common/linux.conf:
/usr/share/qt5/mkspecs/common/gcc-base.conf:
/usr/share/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt5/mkspecs/common/g++-base.conf:
/usr/share/qt5/mkspecs/common/g++-unix.conf:
/usr/share/qt5/mkspecs/qconfig.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_bootstrap.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmldevtools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/share/qt5/mkspecs/features/qt_functions.prf:
/usr/share/qt5/mkspecs/features/qt_config.prf:
/usr/share/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/share/qt5/mkspecs/features/spec_post.prf:
/usr/share/qt5/mkspecs/features/exclusive_builds.prf:
/usr/share/qt5/mkspecs/features/default_pre.prf:
/usr/share/qt5/mkspecs/features/unix/default_pre.prf:
/usr/share/qt5/mkspecs/features/release.prf:
/usr/share/qt5/mkspecs/features/default_post.prf:
/usr/share/qt5/mkspecs/features/shared.prf:
/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt5/mkspecs/features/warn_on.prf:
/usr/share/qt5/mkspecs/features/wayland-scanner.prf:
/usr/share/qt5/mkspecs/features/testcase_targets.prf:
/usr/share/qt5/mkspecs/features/exceptions.prf:
/usr/share/qt5/mkspecs/features/yacc.prf:
/usr/share/qt5/mkspecs/features/lex.prf:
test.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 -o Makefile test.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/test1.0.0 || $(MKDIR) .tmp/test1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/test1.0.0/ && (cd `dirname .tmp/test1.0.0` && $(TAR) test1.0.0.tar test1.0.0 && $(COMPRESS) test1.0.0.tar) && $(MOVE) `dirname .tmp/test1.0.0`/test1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/test1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp Game.hpp \
		Tools.hpp \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/half_float.hpp \
		glm/gtc/half_float.inl \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Game.o: Game.cpp Game.hpp \
		Tools.hpp \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/half_float.hpp \
		glm/gtc/half_float.inl \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		Shader.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o Game.cpp

Tools.o: Tools.cpp Tools.hpp \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/half_float.hpp \
		glm/gtc/half_float.inl \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tools.o Tools.cpp

Shader.o: Shader.cpp Shader.hpp \
		Tools.hpp \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/half_float.hpp \
		glm/gtc/half_float.inl \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Shader.o Shader.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

